### ISSUE TITLE
Cropping Option

### ISSUE THREAD

**Issue by cinghaman** [alfg/ffmpeg-commander#16]
Looking at ways to add option to crop the input video at a given time stamp  like crop 10 sec from the video starting at 15min ... 
Also looking at ways to do a dynamic video source input like from a google spreadsheet (picking the files from dropbox).

Do you think your tool could achieve something like that?

**Comment by alfg** [comment]
Hey @cinghaman, 

Can you enable `clip` from the format tab using a start time of: `00:15:00` and stop time of: `00:15:10` to clip the video? It should generate the following output, which you can use to trim your video.
```
ffmpeg -i input.mp4 -ss 00:15:00 -to 00:15:10 -c:v libx264 -c:a copy output.mp4
```

Also, I'm not sure about adding a dynamic video source, since this tool doesn't actually do any processing. Instead it just generates the command for you to run ffmpeg on your machine. The input and output options are a used to populate the input/output when generating the output command.

**Comment by cinghaman** [comment]
> Hey @cinghaman,
> 
> Can you enable `clip` from the format tab using a start time of: `00:15:00` and stop time of: `00:15:10` to clip the video? It should generate the following output, which you can use to trim your video.
> 
> ```
> ffmpeg -i input.mp4 -ss 00:15:00 -to 00:15:10 -c:v libx264 -c:a copy output.mp4
> ```
> 
> Also, I'm not sure about adding a dynamic video source, since this tool doesn't actually do any processing. Instead it just generates the command for you to run ffmpeg on your machine. The input and output options are a used to populate the input/output when generating the output command.

Perfect thanks

**Comment by alfg** [comment]
You're welcome. :) 

Can this be closed?
